# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 8880

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

#logging:
#  level:
#    org.springframework:
#      security: DEBUG